[package]
name = "iso639"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3.15", optional = true }
phf = "0.8.0"

[build-dependencies]
phf_codegen = "0.8.0"
csv = "1.1.3"

[profile.release]
lto = "fat"